# https://houssein.me/continuous-integration-angular-firebase-travisci
sudo: required

language: node_js

node_js:
  - "8.7"

services:
  - docker

cache:
  directories:
    - $(npm config get prefix)/bin/firebase
    - $(npm root)
    - src/node_modules

install:
  - cd src
  - npm install -g firebase-tools
  - npm install

script:
  - npm test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t jabaridash/mazes:${TRAVIS_BUILD_NUMBER} -t jabaridash/mazes .
  - docker push jabaridash/mazes:${TRAVIS_BUILD_NUMBER}
  - cd ${TRAVIS_BUILD_DIR}

deploy:
  - provider: script
    script: firebase deploy --token $FIREBASE_TOKEN
    on:
      branch: master
