# https://houssein.me/continuous-integration-angular-firebase-travisci
sudo: required

language: node_js

node_js:
  - "8.7"

services:
  - docker

cache:
  directories:
    - $(npm config get prefix)/bin/firebase
    - $(npm root)
    - src/node_modules

install:
  - ./install.sh

script:
  - ./test.sh

after_success:
  - ./publish.sh

deploy:
  - provider: script
    script: ./deploy.sh
    on:
      branch: master
