language: ruby

sudo: false

rvm:
- 2.3.3

before_script:
  - bundle install

script:
  - bundle exec jekyll build

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t jabaridash/mazes .
  - docker push jabaridash/mazes

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

on:
  branch: master
