sudo: required

services:
  - docker

language: node_js
node_js:
  - "8.7"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t jabaridash/mazes:$TRAVIS_COMMIT -t jabaridash/mazes .
  - docker run -d --name=mazes -p 8080:80 jabaridash/mazes
  - sleep 5
  - curl localhost:8080

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
#   - docker push jabaridash/mazes:$TRAVIS_COMMIT
#   - docker push jabaridash/mazes
