language: ruby

sudo: false

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

rvm:
- 2.3.3

before_script:
  - bundle install

script:
  - bundle exec jekyll build

deploy:
  skip_cleanup: true
  provider: script
  script: firebase deploy --token "$FIREBASE_TOKEN" --non-interactive --only hosting
  on:
    branch: master
