# https://houssein.me/continuous-integration-angular-firebase-travisci
sudo: required

services:
  - docker

language: node_js
node_js:
  - "8.7"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t jabaridash/mazes:$TRAVIS_COMMIT -t jabaridash/mazes .
  - docker run -d --name=mazes -p 8080:80 jabaridash/mazes
  - sleep 5
  - curl localhost:8080

after_success:
  - docker push jabaridash/mazes:$TRAVIS_COMMIT

deploy:
  - provider: script
    script: docker push jabaridash/mazes && firebase deploy --token $FIREBASE_TOKEN
    on:
      branch: master
