theme: jekyll-theme-cayman

index_page: README.md

baseurl: "/mazes"
url: "https://n02870941.github.io"

show_downloads: true

github:
  zip_url: "https://github.com/N02870941/rpi_cluster/archive/master.zip"
  tar_url: "https://github.com/N02870941/rpi_cluster/archive/master.tar.gz"
  
google_analytics: true
